name: Survival
main: de.greenman1805.survival.Main
version: 1.0
author: Greenman1805

permissions:
  survival.exempt:
    default: op          

commands:
  pvp:
    description: Wechsel zwichen PvP und Passiv Modus